apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: gitops-webapp:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: APP_VERSION
          value: "1.0"
        - name: THEME_NAME
          value: "Blue Theme"
        - name: THEME_COLOR
          value: "#3498db"
