apiVersion: v1
kind: Service
metadata:
  name: flask-demo-service
spec:
  type: LoadBalancer # Also could be NodePort for local dev, LoadBalancer is better for demo
  selector:
    app: flask-demo # This links the service to the deployment pods
  ports:
    - protocol: TCP
      port: 80 # The port exposed locally
      targetPort: 5000 # The port our Docker containers are listening on
