apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  # Replicas set to 0, KEDA will manage this
  replicas: 0
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: worker:latest
        imagePullPolicy: Never
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
